[package]
name = "tokenizing"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.1", default-features = false }
wgpu_glyph = "0.19"
