[package]
name = "bite"
version = "0.10.0"
edition = "2021"

[dependencies]
object = "0.32"
pdb = "0.8"
triple_accel = "0.4"
once_cell = "1.1"
glam = { version = "0.24", features = ["bytemuck"] }
bytemuck = { version = "1.14", default-features = false }
winit = "0.28.6"
wgpu = { version = "0.16"}
png = "0.17"
rfd = "0.12"
pollster = "0.3.0"
egui = { version = "0.22.0", features = ["bytemuck"] }
egui_dock = "0.6"
copypasta = "0.8"

log = { path = "./log" }
debugger = { path = "./debugger" }
decoder = { path = "./decoder" }
disassembler = { path = "./disassembler" }
tokenizing = { path = "./tokenizing" }
symbols = { path = "./symbols" }
dirs = "5"
libc = "0.2.147"

[profile.release]
# strip = true
debug = true
# lto = "thin"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[workspace]
members = [
    "log",
    "disassembler",
    "tokenizing",
    "decoder",
    "decoder-x86_64",
    "decoder-arm",
    "decoder-riscv",
    "decoder-mips",
    "symbols",
    "debugger"
]
