[package]
name = "rustdump"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-demangle = "0.1"
object = "0.29"
pdb = "0.8"
triple_accel = "0.4"
phf = { version = "0.11", features = ["macros"] }
iced = "0.7"
iced_native = "0.8"
once_cell = "1.17"
glam  = "0.22"
bytemuck = "1.13.0"

[dev-dependencies]
lazy_static = "1.4"
