[package]
name = "rustdump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-demangle = "0.1"
phf = { version = "0.10", features = ["macros"] }
goblin = "0.4"
# tokio = { version = "1.0", features = ["full"] }
