[package]
name = "rustdump"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-demangle = "0.1"
object = "0.29"
pdb = "0.8"
triple_accel = "0.4"

[dev-dependencies]
lazy_static = "1.4"
