[package]
name = "bite"
version = "0.4.0"
edition = "2021"

[dependencies]
rustc-demangle = "0.1"
object = "0.29"
pdb = "0.8"
triple_accel = "0.4"
phf = { version = "0.11", features = ["macros"] }
once_cell = "1.17"
glam = { version = "0.22", features = ["bytemuck"] }
bytemuck = { version = "1.13", features = ["derive"] }
winit = "0.28"
wgpu = { version = "0.15", features = ["spirv"] }
naga = { version = "0.11", features = ["glsl-in", "spv-out"] }
tokio = { version = "1.25", features = ["rt-multi-thread", "net", "fs", "io-util", "macros"] }
png = "0.17.7"
ab_glyph = "0.2.20"
rfd = { version = "0.11", features = ["xdg-portal"], default-features = false }

[dependencies.wgpu_glyph]
git = "https://github.com/WINSDK/wgpu_glyph.git"

[profile.release]
strip = true
# lto = "thin"
panic = "abort"

[dev-dependencies]
crc = "3.0"
