[package]
name = "bite"
version = "0.4.0"
edition = "2021"

[dependencies]
object = "0.30"
pdb = "0.8"
triple_accel = "0.4"
once_cell = "1.1"
glam = { version = "0.23", features = ["bytemuck"] }
bytemuck = { version = "1.1", default-features = false }
winit = { version = "0.28.2", features = ["wayland", "x11"], default-features = false }
wgpu = { version = "0.15", features = ["spirv"], default-features = false }
wgpu_glyph = "0.19"
ab_glyph = { version = "0.2", default-features = false }
naga = { version = "0.11", features = ["glsl-in", "spv-out"], default-features = false }
tokio = { version = "1.2", features = ["rt-multi-thread", "fs", "io-util", "macros", "time"] }
png = "0.17"
rfd = "0.11"
bitflags = "2"
disassembler = { path = "./disassembler" }
tokenizing = { path = "./tokenizing" }

[profile.release]
strip = true
# debug = true
# lto = "thin"
panic = "abort"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[workspace]
members = [
    "disassembler",
    "tokenizing",
    "decoder",
    "decoder-x86_64",
    "decoder-arm",
    "decoder-riscv",
    "decoder-mips",
]
