[package]
name = "bite"
version = "0.9.0"
edition = "2021"

[dependencies]
object = "0.30"
pdb = "0.8"
triple_accel = "0.4"
once_cell = "1.1"
glam = { version = "0.23", features = ["bytemuck"] }
bytemuck = { version = "1.13", default-features = false }
winit = "0.28.6"
wgpu = { version = "0.16", default-features = false }
wgpu_glyph = "0.20"
ab_glyph = { version = "0.2", default-features = false }
png = "0.17"
rfd = "0.11"
pollster = "0.3.0"
egui = { version = "0.22.0", features = ["bytemuck"] }
egui_dock = "0.6.1"
copypasta = "0.8"

debugger = { path = "./debugger" }
decoder = { path = "./decoder" }
disassembler = { path = "./disassembler" }
tokenizing = { path = "./tokenizing" }
symbols = { path = "./symbols" }
dirs = "5"
libc = "0.2.147"

[profile.release]
# strip = true
# debug = true
# lto = "thin"
# panic = "abort"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[workspace]
members = [
    "disassembler",
    "tokenizing",
    "decoder",
    "decoder-x86_64",
    "decoder-arm",
    "decoder-riscv",
    "decoder-mips",
    "symbols",
    "debugger"
]
