[package]
name = "bite"
version = "0.13.0"
edition = "2021"

[dependencies]
object = { workspace = true }
pdb = { workspace = true }
once_cell = { workspace = true }
nix = { workspace = true }
png = "0.17"
rfd = "0.12"

commands = { path = "./commands" }
log = { path = "./log" }
gui = { path = "./gui" }
decoder = { path = "./decoder" }
tokenizing = { path = "./tokenizing" }
symbols = { path = "./symbols" }

# tracing-tracy = "0.10.4"
# tracing-subscriber = { version = "0.3", default-features = false }
# tracing = "0.1"

[profile.release]
# strip = true
debug = true
# lto = "thin"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[workspace]
resolver = "2"
members = [
    "log",
    "gui",
    "commands",
    "tokenizing",
    "decoder",
    "decoder-x86_64",
    "decoder-arm",
    "decoder-riscv",
    "decoder-mips",
    "symbols",
    "debugger",
    "processor",
    "processor_types"
]

[workspace.dependencies]
egui = { version = "0.25", features = ["bytemuck"], default-features = false }
crossbeam-queue = "0.3"
object = "0.32"
gimli = "0.28"
pdb = { git = "https://github.com/WINSDK/pdb-rs" }
once_cell = "1.18"
nix = { git = "https://github.com/mbyzhang/nix" }
