[package]
name = "bite"
version = "0.13.0"
edition = "2021"

[dependencies]
object = { workspace = true }
pdb = { workspace = true }
once_cell = { workspace = true }
png = "0.17"
rfd = "0.12"

commands = { path = "./commands" }
log = { path = "./log" }
gui = { path = "./gui" }
decoder = { path = "./decoder" }
disassembler = { path = "./disassembler" }
tokenizing = { path = "./tokenizing" }
symbols = { path = "./symbols" }
libc = "0.2.147"

# tracing-tracy = "0.10.4"
# tracing-subscriber = { version = "0.3", default-features = false }
# tracing = "0.1"

[profile.release]
# strip = true
# debug = true
# lto = "thin"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[workspace]
resolver = "2"
members = [
    "log",
    "gui",
    "commands",
    "disassembler",
    "tokenizing",
    "decoder",
    "decoder-x86_64",
    "decoder-arm",
    "decoder-riscv",
    "decoder-mips",
    "symbols",
    "debugger"
]

[workspace.dependencies]
egui = { version = "0.24", features = ["bytemuck"], default-features = false }
crossbeam-queue = "0.3"
object = "0.32"
pdb = "0.8"
once_cell = "1.18"
