[package]
name = "bite"
version = "0.11.0"
edition = "2021"

[dependencies]
object = "0.32"
pdb = "0.8"
once_cell = "1.1"
png = "0.17"
rfd = "0.12"

args = { path = "./args" }
log = { path = "./log" }
gui = { path = "./gui" }
decoder = { path = "./decoder" }
disassembler = { path = "./disassembler" }
tokenizing = { path = "./tokenizing" }
symbols = { path = "./symbols" }
libc = "0.2.147"

[profile.release]
# strip = true
# debug = true
# lto = "thin"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[workspace]
resolver = "2"
members = [
    "log",
    "gui",
    "args",
    "disassembler",
    "tokenizing",
    "decoder",
    "decoder-x86_64",
    "decoder-arm",
    "decoder-riscv",
    "decoder-mips",
    "symbols",
    "debugger"
]

[workspace.dependencies]
egui = { version = "0.24", features = ["bytemuck"] }
