[package]
name = "bite"
version = "0.7.0"
edition = "2021"

[dependencies]
object = "0.30"
pdb = "0.8"
triple_accel = "0.4"
once_cell = "1.1"
glam = { version = "0.23", features = ["bytemuck"] }
bytemuck = { version = "1.1", default-features = false }
winit = "0.28.6"
wgpu = { version = "0.16", default-features = false }
wgpu_glyph = "0.20"
ab_glyph = { version = "0.2", default-features = false }
png = "0.17"
rfd = "0.11"
pollster = "0.3.0"
decoder = { path = "./decoder" }
disassembler = { path = "./disassembler" }
tokenizing = { path = "./tokenizing" }
symbols = { path = "./symbols" }

[profile.release]
strip = true
# debug = true
# lto = "thin"
panic = "abort"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[workspace]
members = [
    "disassembler",
    "tokenizing",
    "decoder",
    "decoder-x86_64",
    "decoder-arm",
    "decoder-riscv",
    "decoder-mips",
    "symbols",
]
