[package]
name = "x86_64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decoder = { path = "../decoder" }
yaxpeax-x86 = { version = "1.1", features = ["std", "colors", "fmt"], default-features = false }
