[package]
name = "x86_64"
version = "0.0.0"
edition = "2021"

[dependencies]
decoder = { path = "../decoder" }
tokenizing = { path = "../tokenizing" }
debugvault = { path = "../debugvault" }
config = { path = "../config" }
