[package]
name = "commands"
version = "0.0.0"
edition = "2021"

[dependencies]
triple_accel = "0.4"
debugvault = { path = "../debugvault" }
log = { path = "../log" }
dirs = { workspace = true }
once_cell = { workspace = true }
egui = { workspace = true }
