[package]
name = "symbols"
version = "0.0.0"
edition = "2021"

[dependencies]
log = { path = "../log" }
tokenizing = { path = "../tokenizing" }
bitflags = "2"
object = { workspace = true }
pdb = { workspace = true }
