[package]
name = "config"
version = "0.0.0"
edition = "2021"

[dependencies]
once_cell = { workspace = true }
egui = { workspace = true }
dirs = { workspace = true }
log = { path = "../log" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
