name: CI
on:
  - pull_request
  - push
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Checking out rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - name: Caching cargo
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Checking out rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Add aditional rustc target's
        run: |
          rustup target add riscv64gc-unknown-none-elf
      - name: Caching cargo
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test
