name: CI
on:
  - pull_request
  - push
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Checking out rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - name: Retrieving cache
        uses: Swatinem/rust-cache@v2
      - name: Formatting
        run: cargo fmt --all -- --check
      - name: Reject unformatted code
        run: git diff --exit-code
      - name: Build
        run: cargo build
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Checking out rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Retrieving cache
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test
