name: CI
on:
  - pull_request
  - push
env:
  CARGO_TERM_COLOR: always
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Checking out rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - name: Caching cargo
        uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        run: |
          sudo apt-get install libgtk-3-dev
      - name: Build
        run: cargo build
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Checking out rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - name: Caching cargo
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Checking out rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - name: Caching cargo
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Checking out rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Add aditional rustc target's
        run: |
          rustup target add riscv64gc-unknown-none-elf
      - name: Caching cargo
        uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        run: |
          sudo apt-get install libgtk-3-dev
      - name: Test
        run: cargo test --workspace --lib
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Checking out rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Add aditional rustc target's
        run: |
          rustup target add riscv64gc-unknown-none-elf
      - name: Caching cargo
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test --workspace --lib
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Checking out rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Add aditional rustc target's
        run: |
          rustup target add riscv64gc-unknown-none-elf
      - name: Caching cargo
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test --workspace --lib
